name: Deploy

on:
  push:
    branches: [master]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Setup .NET Core ğŸ”§
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build and Package ğŸ”¨
        run: ./build.sh
      - name: Upload package ğŸ“¦
        uses: actions/upload-artifact@v1
        with:
          name: Rebuild
          path: Source/Service/bin/Release/netcoreapp3.1/Rebuild.zip
      
  deploy-to-stage:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Download package ğŸ“¦
      uses: actions/download-artifact@v1
      with:
        path: Source/Service/bin/Release/netcoreapp3.1
        name: Rebuild
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install ğŸ”§
      run: npm install
    - name: npm install dependencies ğŸ”§
      run: npm i serverless-api-stage
    - name: Serverless Deploy ğŸš€
      uses: aaronpanch/action-serverless@v1.0.0
      with:
        args: deploy --stage Staging --config stage.serverless.yml
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_SECRET_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_SECRET_KEY }}
    - name: Serverless Deploy ğŸš€
      uses: aaronpanch/action-serverless@v1.0.0
      with:
        args: deploy --stage Staging --config stage_authorizer.serverless.yml
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_SECRET_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_SECRET_KEY }}
        
  end-to-end-test:
    runs-on: ubuntu-latest
    needs: [deploy-to-stage]
    steps:
      - name: Set up Python 3.7 ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies ğŸ”§
        run: |
          python -m pip install --upgrade pip
          pip install glasswall-aws-product-test-automation
      - name: Run Tests ğŸ§ª
        run: s93_test_automation --product "rebuild" --key_type "x_api_key" --endpoint "${{ secrets.STAGE_API_KEY_ENDPOINT }}" --jwt_token "${{ secrets.STAGE_JWT_TOKEN }}" --x_api_key "${{ secrets.STAGE_API_KEY }}" --api_key "${{ secrets.STAGE_API_KEY }}" --invalid_token "abc"
      - name: Run Tests ğŸ§ª
        run: s93_test_automation --product "rebuild" --key_type "jwt_token" --endpoint "${{ secrets.STAGE_API_JWT_ENDPOINT }}" --jwt_token "${{ secrets.STAGE_JWT_TOKEN }}" --x_api_key "${{ secrets.STAGE_API_KEY }}" --api_key "${{ secrets.STAGE_API_KEY }}" --invalid_token "abc"
   
  deploy-to-prod-1:
    runs-on: ubuntu-latest
    needs: [end-to-end-test]
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Download package ğŸ“¦
      uses: actions/download-artifact@v1
      with:
        path: Source/Service/bin/Release/netcoreapp3.1
        name: Rebuild
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install ğŸ”§
      run: npm install
    - name: npm install dependencies ğŸ”§
      run: npm i serverless-api-stage
    - name: Serverless Deploy ğŸš€
      uses: aaronpanch/action-serverless@v1.0.0
      with:
        args: deploy --stage Prod --config prod.serverless.yml
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD1_SECRET_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD1_SECRET_KEY }}
    - name: Serverless Deploy ğŸš€
      uses: aaronpanch/action-serverless@v1.0.0
      with:
        args: deploy --stage Prod --config prod_authorizer.serverless.yml
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD1_SECRET_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD1_SECRET_KEY }}
       
